version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Build started on `date`"
      - cd frontend
      - echo "No build process needed for static website"

      - echo "Injecting API Key..."
      - sed -i "s|YOUR_API_GATEWAY_ENDPOINT|${API_ENDPOINT}|g" app.js
      - sed -i "s|YOUR_API_KEY|${API_KEY}|g" app.js
      - sed -i "s|YOUR_PHOTOS_BUCKET_NAME|${PHOTOS_BUCKET}|g" app.js


  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Uploading to S3..."
      - aws s3 sync . s3://${FRONTEND_BUCKET_NAME}/ --exclude ".git/*" --exclude "buildspec.yml"
      - echo "Frontend deployed successfully"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - .git/**/*
    - buildspec.yml
