version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - cd lambda/index-photos
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Packaging Lambda function..."
      - zip -r search-photos.zip . -x "*.git*" "buildspec.yml"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - search-photos.zip
  base-directory: ./lambda/search-photos/
